perf: add meta tags
vitessio/arewefastyet pull request #419
Opened 2023-08-07 17:22 UTC by Lucif3r-in

Added meta tags to improve website visibility when shared.
We can also add the tags to the react-version of the website if approved.

2023-08-07 20:40 UTC, frouioui requested changes
Thanks @Lucif3r-in for this first contribution. The web server under `./go/server` will soon be removed. It has been replaced by the React project in `./website`. Can you add the meta tags there?

2023-08-08 11:59 UTC, Lucif3r-in commented
> Thanks @Lucif3r-in for this first contribution. The web server under `./go/server` will soon be removed. It has been replaced by the React project in `./website`. Can you add the meta tags there?

Sure I was going to do that in the next step, was just waiting for your approval. Will do it ASAP.

2023-08-08 15:25 UTC, Lucif3r-in commented
@frouioui @GuptaManan100 Done changes as suggested.

2023-08-08 16:25 UTC, frouioui commented on website/public/img/favicon.png
Let's move both images to the `website/src/assets` directory, we already have a few images there. At the same time, you can remove the `website/public/` directory entirely to avoid future confusion.

2023-08-08 16:26 UTC, frouioui approved these changes
Approving this PR for now, I'll merge it once all comments have been addressed. Thanks @Lucif3r-in for this helpful contribution!

2023-08-08 16:27 UTC, Lucif3r-in commented on website/public/img/favicon.png
Ok, on it!!

2023-08-08 16:35 UTC, Lucif3r-in commented
> Approving this PR for now, I'll merge it once all comments have been addressed. Thanks @Lucif3r-in for this helpful contribution!

Sure, I have made the suggested changes🚀🚀

2023-08-08 18:41 UTC, frouioui approved these changes

2023-08-08 18:41 UTC, frouioui commented
awesome, thank you @Lucif3r-in !

2023-08-08 18:41 UTC, merged